version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'AFnet-api-server'
    working_dir: '/opt/'
    tty: true
    ports:
      - "80:80"
    volumes:
      - /opt/api/src/:/opt
      - /mnt/data:/opt/static/