version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'AFnet-api-server'
    working_dir: '/api/'
    tty: true
    ports:
      - "80:80"
    volumes:
      - /opt/api/src/:/api
      - /mnt/data:/api/static/