name: Auto deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: repo clone
        run: |
          git clone https://github.com/chan-mai/AFnet-api
      - name: copy files
        run: |
          cp -f -r ./AFnet-api/* /opt/AFnet-api/
      - name: docker-compose build
        run: |
          docker-compose up -f /opt/AFnet-api/docker-compose.yml -d --build
      - name: delete files
        run: |
          rm -rf ./AFnet-api
