name: Auto deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: repo clone
        run: |
          git clone https://github.com/chan-mai/AFnet-api
      - name: copy files
        run: |
          cp -f ./AFnet-api/* /opt/AFnet-api/
      - name: change dic
        run: |
          cd /opt/AFnet-api/
      - name: docker-compose build
        run: |
          docker-compose up -d --build
